// app/freeModels.ts
export const FREE_MODELS = [
  "deepseek/deepseek-r1:free",
  "google/gemini-2.5-flash-image-preview:free",
  "qwen/qwen3-coder:free",
  "tngtech/deepseek-r1t-chimera:free",
  "tngtech/deepseek-r1t2-chimera:free",
  "z-ai/glm-4.5-air:free",
  "google/gemma-3-4b-it:free",
  "google/gemma-3-12b-it:free",
  "google/gemma-3-27b-it:free",
  "google/gemma-3n-e2b-it:free",
  "google/gemma-3n-e4b-it:free",
  "meta-llama/llama-3.1-405b-instruct:free",
  "meta-llama/llama-3.2-3b-instruct:free",
  "meta-llama/llama-3.3-70b-instruct:free",
  "meta-llama/llama-3.3-8b-instruct:free",
  "meta-llama/llama-4-maverick:free",
  "meta-llama/llama-4-scout:free",
  "microsoft/mai-ds-r1:free",
  "mistralai/devstral-small-2505:free",
  "mistralai/mistral-7b-instruct:free",
  "moonshotai/kimi-vl-a3b-thinking:free",
  "nousresearch/deephermes-3-llama-3-8b-preview:free",
  "tencent/hunyuan-a13b-instruct:free",
];
