import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://tomatoai.in'
  
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
          '/*.json$',
          '/search?q=*',
          '/filter/*',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
        ],
      },
      {
        userAgent: 'Slurp',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
        ],
      },
      {
        userAgent: 'DuckDuckBot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
        ],
      },
      {
        userAgent: 'Baiduspider',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
        ],
      },
      {
        userAgent: 'YandexBot',
        allow: '/',
        disallow: [
          '/api/',
          '/admin/',
          '/_next/',
          '/static/',
          '/temp/',
          '/private/',
          '/auth/',
          '/login',
          '/signup',
          '/dashboard',
          '/profile',
          '/settings',
        ],
      },
      // Block crawlers that don't follow robots.txt well
      {
        userAgent: [
          'AhrefsBot',
          'MJ12bot',
          'DotBot',
          'BlexBot',
          'BacklinkCrawler',
          'SemrushBot',
          'SEOkicks-Robot',
          'CCBot',
          'ChatGPT-User',
          'GPTBot',
          'Google-Extended',
          'anthropic-ai',
          'Claude-Web',
        ],
        disallow: '/',
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl,
  }
}
